### PR TITLE
303011 updated deps.json to point to full github path

### PR DESCRIPTION
**Pull request by Nino-K**

### CODE REVIEW

**Comment by philwhln** [comment]
Why was this merged to master? I don't see any code review on this

**Comment by Nino-K** [comment]
@aarondl  this is why I was emphasizing comment in the PR.

**Comment by aarondl** [comment]
@philwhln I had looked at this, the LGTM was in OP but not here. Guess we need to put it in both?

**Comment by philwhln** [comment]
> Guess we need to put it in both?

For me, here is more important than OP.

Maybe with Jira we can do some API magic, so we update both places automatically based perception your mood while looking at the code? :thought_balloon:

**Comment by aarondl** [comment]
No API magic necessary. JIRA has lots of github integration points \o/

**Pull request merged**
